name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

  install:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install dependencies
        run: |
          npm cache clean --force
          if [ -f package.json ]; then
            npm install
          else
            echo "package.json not found, skipping npm install"
          fi
        working-directory: ./
      - name: Save npm error log
        if: failure()
        run: cp /home/runner/.npm/_logs/*-debug-0.log ./npm-error.log
        working-directory: ./

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Run ESLint
        run: npm run lint
        working-directory: ./

  compile:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Compile TypeScript
        run: npm run compile
        working-directory: ./

  test:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Run tests
        run: npm test
        working-directory: ./

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Package VSCode extension
        run: npm run package
        working-directory: ./

  upload:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v2
        with:
          name: vsix
          path: '*.vsix'

  version:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Bump version
        run: npm run version
        working-directory: ./

  changelog:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Generate changelog
        run: npm run changelog
        working-directory: ./

  error-report:
    runs-on: ubuntu-latest
    needs: [install, lint, compile, test, package, upload, version, changelog]
    if: failure()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm cache clean --force
          if [ -f package.json ]; then
            npm install
          else
            echo "package.json not found, skipping npm install"
          fi
        working-directory: ./

      - name: Ensure bugreport.json is created
        run: |
          if [ ! -f ./bugreport.json ]; then
            echo '{"issue_number": 0}' > ./bugreport.json
          fi
        working-directory: ./

      - name: Create bug report
        run: npm run create-bugreport
        working-directory: ./

      - name: Attach npm error log to GitHub issue
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ISSUE_NUMBER=$(node -e "console.log(require('./bugreport.json').issue_number)")
          gh issue comment $ISSUE_NUMBER --body "$(cat npm-error.log)"
        working-directory: ./
